name: procura
description: Mobile Application for Procura.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.0.2
  dynamic_theme: ^1.0.0
  charts_flutter: ^0.5.0
  flutter_sparkline: ^0.1.0
  flutter_circular_chart: ^0.1.0
  chartjs: ^0.5.0
  badges: ^0.0.6
  open_file: ^1.1.1
  flutter_pdf_viewer: ^0.0.4
  url_launcher: ^4.0.3
  file_picker: ^1.1.1
  path_provider: ^0.4.1
  shared_preferences: ^0.4.2
  wifi: ^0.1.2
  get_ip: ^0.1.0
  simple_permissions: ^0.1.6

  dio: any

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
      - assets/images/
      - assets/icons/
      - assets/files/
      - assets/files/Bernabe1.docx
  fonts:
      - family: Raleway
        fonts:
          - asset: assets/fonts/Raleway-Regular.ttf
      - family: Lulo
        fonts:
          - asset: assets/fonts/Lulo.otf
      - family: Montserrat
        fonts:
          - asset: assets/fonts/Montserrat-ExtraLight.otf
          - asset: assets/fonts/Montserrat-Regular.otf
          - asset: assets/fonts/Montserrat-Thin.otf

      - family:  CustomIcons
        fonts:
          - asset: assets/icons/fonts/CustomIcons.ttf
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

